POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"kdfkiwkl#9023kldlk"
}


###

POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"kdfkiwkl#9023kldlk",
    "name":"testers"
}

###

POST http://localhost:8080/auth/changePassword
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwidXNlcklkIjoiNjIwMzJiMzdjOTExNDU4NTcyMTUwZTlmIiwiaXNNb2QiOmZhbHNlLCJpYXQiOjE2NDQzNzQ4NTMsImV4cCI6MTY0NDM3ODQ1M30.6zt0Kp3jsxh6ieBOcpHXeTUrdQMOcUfdPaciqZr1Mvw

{
    "oldPassword":"kdfkiwkl#9023kldlk",
    "newPassword":"kdfkiwkl#9023kldlk"
}

###

POST http://localhost:8080/search
Content-Type: application/json

{
    
}
